// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVSYxn35EhfkqqC7RSTEQN6icvOu4vM1w',
    appId: '1:28948097719:web:6a5b543ca3ab9ae56d7b32',
    messagingSenderId: '28948097719',
    projectId: 'collegeconnect-2437f',
    authDomain: 'collegeconnect-2437f.firebaseapp.com',
    storageBucket: 'collegeconnect-2437f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGb7Vl8ECj9W_LQ_OL_PVXv5OoBUYd_nA',
    appId: '1:28948097719:android:29984dbda55666d46d7b32',
    messagingSenderId: '28948097719',
    projectId: 'collegeconnect-2437f',
    storageBucket: 'collegeconnect-2437f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYkO7CHezZnEVGzzvJSbLEI_jkxnLz-s',
    appId: '1:28948097719:ios:c8813b1dab3ee0ae6d7b32',
    messagingSenderId: '28948097719',
    projectId: 'collegeconnect-2437f',
    storageBucket: 'collegeconnect-2437f.firebasestorage.app',
    iosBundleId: 'com.example.collegeconnect',
  );
}
